// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: forestroute/forest_route.proto

package forestroute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Animal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Animal) Reset() {
	*x = Animal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forestroute_forest_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Animal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Animal) ProtoMessage() {}

func (x *Animal) ProtoReflect() protoreflect.Message {
	mi := &file_forestroute_forest_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Animal.ProtoReflect.Descriptor instead.
func (*Animal) Descriptor() ([]byte, []int) {
	return file_forestroute_forest_route_proto_rawDescGZIP(), []int{0}
}

func (x *Animal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type IsAnimalUnknown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Known bool `protobuf:"varint,1,opt,name=known,proto3" json:"known,omitempty"`
}

func (x *IsAnimalUnknown) Reset() {
	*x = IsAnimalUnknown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forestroute_forest_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsAnimalUnknown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAnimalUnknown) ProtoMessage() {}

func (x *IsAnimalUnknown) ProtoReflect() protoreflect.Message {
	mi := &file_forestroute_forest_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAnimalUnknown.ProtoReflect.Descriptor instead.
func (*IsAnimalUnknown) Descriptor() ([]byte, []int) {
	return file_forestroute_forest_route_proto_rawDescGZIP(), []int{1}
}

func (x *IsAnimalUnknown) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

type RouteSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StepsCount int32                  `protobuf:"varint,1,opt,name=StepsCount,proto3" json:"StepsCount,omitempty"`
	Duration   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *RouteSummary) Reset() {
	*x = RouteSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forestroute_forest_route_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSummary) ProtoMessage() {}

func (x *RouteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_forestroute_forest_route_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSummary.ProtoReflect.Descriptor instead.
func (*RouteSummary) Descriptor() ([]byte, []int) {
	return file_forestroute_forest_route_proto_rawDescGZIP(), []int{2}
}

func (x *RouteSummary) GetStepsCount() int32 {
	if x != nil {
		return x.StepsCount
	}
	return 0
}

func (x *RouteSummary) GetDuration() *timestamppb.Timestamp {
	if x != nil {
		return x.Duration
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Start  *Point `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Finish *Point `protobuf:"bytes,3,opt,name=finish,proto3" json:"finish,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forestroute_forest_route_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_forestroute_forest_route_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_forestroute_forest_route_proto_rawDescGZIP(), []int{3}
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetStart() *Point {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Route) GetFinish() *Point {
	if x != nil {
		return x.Finish
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position int32 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forestroute_forest_route_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_forestroute_forest_route_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_forestroute_forest_route_proto_rawDescGZIP(), []int{4}
}

func (x *Point) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

var File_forestroute_forest_route_proto protoreflect.FileDescriptor

var file_forestroute_forest_route_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x66, 0x6f,
	0x72, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c,
	0x0a, 0x06, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0f,
	0x49, 0x73, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x22, 0x66, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x65, 0x70, 0x73, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x65, 0x70, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x71, 0x0a,
	0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x6f, 0x72, 0x65,
	0x73, 0x74, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xd2, 0x01, 0x0a, 0x0b, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x4d, 0x61, 0x6b, 0x65, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x12, 0x12, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x1a, 0x12, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x43,
	0x0a, 0x10, 0x4d, 0x61, 0x6b, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x12, 0x12, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x1a, 0x19, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x13, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x1a, 0x1c, 0x2e, 0x66, 0x6f, 0x72,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x49, 0x73, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f,
	0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_forestroute_forest_route_proto_rawDescOnce sync.Once
	file_forestroute_forest_route_proto_rawDescData = file_forestroute_forest_route_proto_rawDesc
)

func file_forestroute_forest_route_proto_rawDescGZIP() []byte {
	file_forestroute_forest_route_proto_rawDescOnce.Do(func() {
		file_forestroute_forest_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_forestroute_forest_route_proto_rawDescData)
	})
	return file_forestroute_forest_route_proto_rawDescData
}

var file_forestroute_forest_route_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_forestroute_forest_route_proto_goTypes = []interface{}{
	(*Animal)(nil),                // 0: forestroute.Animal
	(*IsAnimalUnknown)(nil),       // 1: forestroute.IsAnimalUnknown
	(*RouteSummary)(nil),          // 2: forestroute.RouteSummary
	(*Route)(nil),                 // 3: forestroute.Route
	(*Point)(nil),                 // 4: forestroute.Point
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_forestroute_forest_route_proto_depIdxs = []int32{
	5, // 0: forestroute.RouteSummary.duration:type_name -> google.protobuf.Timestamp
	4, // 1: forestroute.Route.start:type_name -> forestroute.Point
	4, // 2: forestroute.Route.finish:type_name -> forestroute.Point
	3, // 3: forestroute.ForestRoute.MakeRoute:input_type -> forestroute.Route
	3, // 4: forestroute.ForestRoute.MakeRouteSummary:input_type -> forestroute.Route
	0, // 5: forestroute.ForestRoute.RegisterAnimal:input_type -> forestroute.Animal
	4, // 6: forestroute.ForestRoute.MakeRoute:output_type -> forestroute.Point
	2, // 7: forestroute.ForestRoute.MakeRouteSummary:output_type -> forestroute.RouteSummary
	1, // 8: forestroute.ForestRoute.RegisterAnimal:output_type -> forestroute.IsAnimalUnknown
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_forestroute_forest_route_proto_init() }
func file_forestroute_forest_route_proto_init() {
	if File_forestroute_forest_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forestroute_forest_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Animal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forestroute_forest_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsAnimalUnknown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forestroute_forest_route_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forestroute_forest_route_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forestroute_forest_route_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forestroute_forest_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forestroute_forest_route_proto_goTypes,
		DependencyIndexes: file_forestroute_forest_route_proto_depIdxs,
		MessageInfos:      file_forestroute_forest_route_proto_msgTypes,
	}.Build()
	File_forestroute_forest_route_proto = out.File
	file_forestroute_forest_route_proto_rawDesc = nil
	file_forestroute_forest_route_proto_goTypes = nil
	file_forestroute_forest_route_proto_depIdxs = nil
}
